### ISSUE TITLE
Problems installing ABC using make

### ISSUE THREAD

**Issue by Applonce** [vlab-cs-ucsb/ABC#9]
Hi, 

I am trying to install ABC using the manual guide posted on install.md (auto script does not work since glog no longer has configure.ac and uses cmake). I am getting an error from libtools saying that src/.libs is not found and the make stops. I have not been able to fix it nor I am unaware of what dependencies I am missing. I would be grateful if a solution for this could be told. I have attached the command prompt outputs. 

All dependencies required in install.md are already installed with the latest version. I'm currently using UBUNTU 21.04. I used cmake to make glog as per their installation guide on their repro. For Mona, installation works however the patch command returns saying there are white space errors and it does not do anything further after 2nd retry, it just says patch is not applied.

[autogen.txt](https://github.com/vlab-cs-ucsb/ABC/files/6520662/autogen.txt)
[configure.txt](https://github.com/vlab-cs-ucsb/ABC/files/6520663/configure.txt)
[make.txt](https://github.com/vlab-cs-ucsb/ABC/files/6520664/make.txt)
[patch.txt](https://github.com/vlab-cs-ucsb/ABC/files/6520674/patch.txt)

Thanks and regards,

Arun

**Comment by william-eiers** [comment]
Hi Arun,

Thank you for interest in ABC! It looks like the change in automake versions in the more recent Ubuntu releases caused the build to fail. I just pushed a fix earlier today which should resolve the issue (tested on both Ubuntu 20.04 and 21.04). You might need to rebuild ABC from scratch (make clean, then follow the build instructions but just for ABC this time). 

For the MONA patch, the two whitespace errors from git apply don't matter in this case. I've updated the installation guide so that the errors are ignored (as they don't affect the MONA installation). 

Also, thanks for the heads up on the Glog installation. I've updated the build instructions accordingly. I'll update the build script in the next week or so to reflect these changes, but for now just following the manual installation instructions should work fine.

Let me know if you have any other issues!

**Comment by Applonce** [comment]
Hi William, 

First and foremost, thanks for your swift response. I really appreciate it. Make all does seem to install properly now however libtool is giving this warning. Do let me know if this is alright to ignore.

libtool: warning: '-version-info/-version-number' is ignored for convenience libraries

Furthermore, As per the SPF-ABC guide, I cant seem to run the examples using 'jpf'. Terminal states that jpf can not be found. As such I tried re-installing everything again to no avail. Any help you can provide on this? I did try to run the jpf command frm jp-core and jpf-symbc directories. 

Thanks and regards,

Arun

**Comment by william-eiers** [comment]
The libtool warning can be ignored. I'll fix it so that warning won't appear in the future.

For SPF, you installed both jpf/spf and populated the site.properties file, is that right? Then to run the examples you would use the jpf binary in the jpf-core/bin folder. i.e.,

<jpf-core root directory>bin/jpf <jpf-symbc root directory>/src/examples/<string jpf file>

If you add the jpf binary to your $PATH then you could just do:

jpf <jpf-symbc root directory>/src/examples/<string jpf file>

To add to the $PATH, put this line in your .bashrc and start a new terminal:

export PATH=$PATH:<absolute path to JPF-core>/bin/

Hope that helps!

**Comment by Applonce** [comment]
Hi,

Thanks for the help once again! I have solved the issues mentioned above. However, now I am getting missing class problems. I am trying to test out the string examples under /src/examples/string at jpf-symbc. There seems to be a missing class for TimingChannelListener. Most of the examples work if this is removed however, I do need the stats for the execution time of the program. In the examples there are 3 different type of listeners which are 

listener = gov.nasa.jpf.symbc.sequences.TimingChannelListener
listener = sidechannel.TimingChannelListener
listener=sidechannel.abc.TimingSideChannelListener

in which I am confused on what I am missing out since I am not able to find the respective classes in the folders. I have attached the command output file for your reference. All 3 lines above return the same type of error (missing class).

Thanks,

Arun

[test.txt](https://github.com/vlab-cs-ucsb/ABC/files/6552994/test.txt)

**Comment by Applonce** [comment]
Hi, 

For the part of implementing model counting with SPF, u said in the readme that I would have to code by my self for it to work. Could u explain it in more details? (sorry I have to ask u directly as google has very vague information on this). 

Thanks and regards,

Arun

**Comment by Applonce** [comment]
fixed by installing jpf-security. Thanks for all the help previously
